/**
 * Renders parsed learning-loop entries into the generated INDEX.md content.
 *
 * The output is a pure function of the entry list: fixed frontmatter (`generated: true`, no `last_reviewed`), a fixed header that points maintainers
 * at `goat-flow index` and `goat-flow stats --check`, and one row per entry in the shared
 * `- [Title](file) (search: "...") - hook (date; ~tokens)` schema (with quote-aware wrapping - see {@link quoteAnchor}).
 *
 * No clock-derived values may appear here - `index-fresh` string-compares a regeneration against the on-disk file, so any nondeterminism reads as
 * permanent staleness. Dates and costs are parsed from entry text.
 */
import type { IndexBucket, IndexEntry } from "./parse-bucket.js";

/** H1 title per generated bucket index. */
const BUCKET_TITLES: Record<IndexBucket, string> = {
  footguns: "Footguns Index",
  lessons: "Lessons Index",
  patterns: "Patterns Index",
  decisions: "Decisions Index",
};

/** What one row points at, phrased per bucket so a cold agent knows why it would open the file. */
const BUCKET_ROW_NOUN: Record<IndexBucket, string> = {
  footguns: "one active footgun entry",
  lessons: "one lesson entry",
  patterns: "one pattern entry",
  decisions: "one Architectural Decision Record with its current status",
};

/** Row hooks stay at 100 characters because every skill reads the generated index before deciding which entry to open. */
const ROW_HOOK_MAX_CHARS = 100;

/** Label that distinguishes future guidance from an incident or context summary. */
const DECISION_HOOK_PREFIX = "Decision: ";

/**
 * Render one generated bucket index from its parsed entries.
 *
 * @param bucket - which learning-loop bucket the index covers; selects title and row description
 * @param entries - parsed active entries in their deterministic parse order
 * @returns full INDEX.md content including frontmatter and a trailing newline
 */
export function formatIndex(
  bucket: IndexBucket,
  entries: IndexEntry[],
): string {
  const header = [
    "---",
    "category: index",
    `bucket: ${bucket}`,
    "generated: true",
    "---",
    "",
    `# ${BUCKET_TITLES[bucket]}`,
    "",
    `Generated by \`goat-flow index\`; do not edit by hand. Each row below maps ${BUCKET_ROW_NOUN[bucket]} to its source file with a grep-friendly \`(search: "...")\` anchor. Re-run \`goat-flow index\` after adding, editing, renaming, or resolving entries - \`goat-flow stats --check\` fails while this file is stale. Live entry counts and freshness come from \`goat-flow stats\`.`,
    "",
  ];
  const rows =
    entries.length === 0
      ? ["_No active entries._"]
      : entries.map((entry) => {
          const selectedHook = formatEntryHook(bucket, entry);
          return `- [${entry.title}](${entry.sourceFile}) (search: ${quoteAnchor(entry.anchor)}) - ${selectedHook}${formatRowSuffix(entry)}`;
        });
  return [...header, ...rows].join("\n") + "\n";
}

/**
 * Choose the single routing hook a reader sees before opening an entry.
 * Footgun and lesson guidance replaces incident prose; other buckets retain their established hook.
 *
 * @param bucket - generated index whose reader contract decides whether guidance is eligible
 * @param entry - parsed row including the legacy hook and optional future action
 * @returns one bounded reader-facing hook
 */
function formatEntryHook(bucket: IndexBucket, entry: IndexEntry): string {
  // Footgun and lesson readers get the future action only when the source declares one.
  if (
    (bucket === "footguns" || bucket === "lessons") &&
    entry.decisionChanged !== null
  ) {
    return formatDecisionHook(entry.decisionChanged);
  }

  return entry.hook;
}

/**
 * Fit future guidance inside the shared row-hook budget without splitting words or inline code.
 * Use when a footgun or lesson tells a reader which action changes next.
 *
 * @param decisionChanged - declared future action; callers use the legacy hook when it is absent
 * @returns labelled guidance no longer than the shared row-hook ceiling
 */
function formatDecisionHook(decisionChanged: string): string {
  const decisionTextMaxChars = ROW_HOOK_MAX_CHARS - DECISION_HOOK_PREFIX.length;

  // Guidance that fits reaches the reader verbatim, including any complete inline code spans.
  if (decisionChanged.length <= decisionTextMaxChars) {
    return `${DECISION_HOOK_PREFIX}${decisionChanged}`;
  }

  const truncatedTextMaxChars = decisionTextMaxChars - 1;
  const candidateText = decisionChanged.slice(0, truncatedTextMaxChars);
  const lastWordBoundary = candidateText.lastIndexOf(" ");
  const completeWords = candidateText.slice(
    0,
    lastWordBoundary > 0 ? lastWordBoundary : 0,
  );
  const openCodeSpanStart = findOpenCodeSpanStart(completeWords);

  // A word boundary inside inline code backs up before its opening delimiter so the reader never sees a broken fragment.
  if (openCodeSpanStart !== null) {
    return `${DECISION_HOOK_PREFIX}${completeWords.slice(0, openCodeSpanStart).trimEnd()}…`;
  }

  return `${DECISION_HOOK_PREFIX}${completeWords}…`;
}

/**
 * Find an inline-code delimiter that remains open at the proposed cut.
 * A null result means the candidate ends outside inline code from the reader's perspective.
 *
 * @param candidateText - decision text already limited to the available row budget
 * @returns opening delimiter offset, or null when every code span is complete
 */
function findOpenCodeSpanStart(candidateText: string): number | null {
  let openDelimiterLength: number | null = null;
  let openDelimiterStart: number | null = null;

  // Delimiter runs are paired by width because Markdown code spans may use one or more backticks.
  for (const delimiterMatch of candidateText.matchAll(/`+/gu)) {
    const delimiterLength = delimiterMatch[0].length;

    // With no open span, this delimiter starts code that must either close or be removed from the row.
    if (openDelimiterLength === null) {
      openDelimiterLength = delimiterLength;
      openDelimiterStart = delimiterMatch.index;
      continue;
    }

    // Only a delimiter of the same width closes the active Markdown code span.
    if (delimiterLength === openDelimiterLength) {
      openDelimiterLength = null;
      openDelimiterStart = null;
    }
  }

  return openDelimiterStart;
}

/** Render the fixed row suffix, omitting only an undeclared date. */
function formatRowSuffix(entry: IndexEntry): string {
  const date = entry.declaredDate === null ? "" : `${entry.declaredDate}; `;
  return ` (${date}~${entry.approxTokenEstimate} tok)`;
}

/**
 * Wrap one anchor for its `(search: ...)` slot: double quotes normally, single quotes when the anchor itself contains only double quotes, and
 * escaped double quotes when both quote types appear.
 * Without this, a title like `"Don't trust me"` would pick a single-quote wrapper and the apostrophe would prematurely close the payload.
 *
 * @param anchor - grep needle from {@link IndexEntry.anchor}
 * @returns the quoted `(search: ...)` payload
 */
function quoteAnchor(anchor: string): string {
  const hasDouble = anchor.includes('"');
  const hasSingle = anchor.includes("'");
  // Prefer a wrapper quote that is absent from the anchor. If both are present,
  // keep the standard double-quote shape and escape only embedded double quotes.
  if (hasDouble && hasSingle) {
    return `"${anchor.replace(/"/gu, '\\"')}"`;
  }
  return hasDouble ? `'${anchor}'` : `"${anchor}"`;
}
